//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MovieData", Namespace="http://schemas.datacontract.org/2004/07/TheaterService")]
    public partial class MovieData : object
    {
        
        private string DescriptionField;
        
        private string GenreField;
        
        private int IdField;
        
        private string ImgPathField;
        
        private int RuntimeField;
        
        private string TitleField;
        
        private ServiceReference1.MovieViewingData[] ViewingField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Genre
        {
            get
            {
                return this.GenreField;
            }
            set
            {
                this.GenreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImgPath
        {
            get
            {
                return this.ImgPathField;
            }
            set
            {
                this.ImgPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Runtime
        {
            get
            {
                return this.RuntimeField;
            }
            set
            {
                this.RuntimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.MovieViewingData[] Viewing
        {
            get
            {
                return this.ViewingField;
            }
            set
            {
                this.ViewingField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MovieViewingData", Namespace="http://schemas.datacontract.org/2004/07/TheaterService")]
    public partial class MovieViewingData : object
    {
        
        private int AvailableSeatsField;
        
        private System.DateTime DateField;
        
        private int IdField;
        
        private int NSeatsField;
        
        private ServiceReference1.SeatData[][] SeatsField;
        
        private string TheaterField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvailableSeats
        {
            get
            {
                return this.AvailableSeatsField;
            }
            set
            {
                this.AvailableSeatsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NSeats
        {
            get
            {
                return this.NSeatsField;
            }
            set
            {
                this.NSeatsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.SeatData[][] Seats
        {
            get
            {
                return this.SeatsField;
            }
            set
            {
                this.SeatsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Theater
        {
            get
            {
                return this.TheaterField;
            }
            set
            {
                this.TheaterField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SeatData", Namespace="http://schemas.datacontract.org/2004/07/TheaterService")]
    public partial class SeatData : object
    {
        
        private int IdField;
        
        private bool IsBookedField;
        
        private int NumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBooked
        {
            get
            {
                return this.IsBookedField;
            }
            set
            {
                this.IsBookedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/TheaterService")]
    public partial class Customer : object
    {
        
        private ServiceReference1.Booking[] BookingField;
        
        private string EmailField;
        
        private int IdField;
        
        private string NameField;
        
        private string PasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Booking[] Booking
        {
            get
            {
                return this.BookingField;
            }
            set
            {
                this.BookingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Booking", Namespace="http://schemas.datacontract.org/2004/07/TheaterService")]
    public partial class Booking : object
    {
        
        private ServiceReference1.Customer CustomerField;
        
        private System.Nullable<int> CustomerIDField;
        
        private int IdField;
        
        private ServiceReference1.Seat[] SeatField;
        
        private ServiceReference1.Viewing ViewingField;
        
        private System.Nullable<int> ViewingIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Customer Customer
        {
            get
            {
                return this.CustomerField;
            }
            set
            {
                this.CustomerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CustomerID
        {
            get
            {
                return this.CustomerIDField;
            }
            set
            {
                this.CustomerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Seat[] Seat
        {
            get
            {
                return this.SeatField;
            }
            set
            {
                this.SeatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Viewing Viewing
        {
            get
            {
                return this.ViewingField;
            }
            set
            {
                this.ViewingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ViewingID
        {
            get
            {
                return this.ViewingIDField;
            }
            set
            {
                this.ViewingIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Viewing", Namespace="http://schemas.datacontract.org/2004/07/TheaterService")]
    public partial class Viewing : object
    {
        
        private ServiceReference1.Booking[] BookingField;
        
        private System.Nullable<System.DateTime> DateField;
        
        private int IdField;
        
        private ServiceReference1.Movie MovieField;
        
        private System.Nullable<int> MovieIDField;
        
        private ServiceReference1.Theater TheaterField;
        
        private System.Nullable<int> TheaterIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Booking[] Booking
        {
            get
            {
                return this.BookingField;
            }
            set
            {
                this.BookingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Movie Movie
        {
            get
            {
                return this.MovieField;
            }
            set
            {
                this.MovieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MovieID
        {
            get
            {
                return this.MovieIDField;
            }
            set
            {
                this.MovieIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Theater Theater
        {
            get
            {
                return this.TheaterField;
            }
            set
            {
                this.TheaterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TheaterID
        {
            get
            {
                return this.TheaterIDField;
            }
            set
            {
                this.TheaterIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Seat", Namespace="http://schemas.datacontract.org/2004/07/TheaterService")]
    public partial class Seat : object
    {
        
        private ServiceReference1.Booking[] BookingField;
        
        private int IdField;
        
        private System.Nullable<int> NumberField;
        
        private System.Nullable<int> RowField;
        
        private ServiceReference1.Theater TheaterField;
        
        private System.Nullable<int> TheaterIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Booking[] Booking
        {
            get
            {
                return this.BookingField;
            }
            set
            {
                this.BookingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Row
        {
            get
            {
                return this.RowField;
            }
            set
            {
                this.RowField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Theater Theater
        {
            get
            {
                return this.TheaterField;
            }
            set
            {
                this.TheaterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TheaterID
        {
            get
            {
                return this.TheaterIDField;
            }
            set
            {
                this.TheaterIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Theater", Namespace="http://schemas.datacontract.org/2004/07/TheaterService")]
    public partial class Theater : object
    {
        
        private int IdField;
        
        private string NameField;
        
        private ServiceReference1.Seat[] SeatField;
        
        private ServiceReference1.Viewing[] ViewingField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Seat[] Seat
        {
            get
            {
                return this.SeatField;
            }
            set
            {
                this.SeatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Viewing[] Viewing
        {
            get
            {
                return this.ViewingField;
            }
            set
            {
                this.ViewingField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movie", Namespace="http://schemas.datacontract.org/2004/07/TheaterService")]
    public partial class Movie : object
    {
        
        private string DescriptionField;
        
        private string GenreField;
        
        private int IdField;
        
        private string ImgPathField;
        
        private int RuntimeField;
        
        private string TitleField;
        
        private ServiceReference1.Viewing[] ViewingField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Genre
        {
            get
            {
                return this.GenreField;
            }
            set
            {
                this.GenreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImgPath
        {
            get
            {
                return this.ImgPathField;
            }
            set
            {
                this.ImgPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Runtime
        {
            get
            {
                return this.RuntimeField;
            }
            set
            {
                this.RuntimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Viewing[] Viewing
        {
            get
            {
                return this.ViewingField;
            }
            set
            {
                this.ViewingField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerData", Namespace="http://schemas.datacontract.org/2004/07/TheaterService")]
    public partial class CustomerData : object
    {
        
        private ServiceReference1.Booking[] BookingField;
        
        private string EmailField;
        
        private int IdField;
        
        private string NameField;
        
        private string PasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Booking[] Booking
        {
            get
            {
                return this.BookingField;
            }
            set
            {
                this.BookingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookingData", Namespace="http://schemas.datacontract.org/2004/07/TheaterService")]
    public partial class BookingData : object
    {
        
        private int IdField;
        
        private int[] SeatsField;
        
        private ServiceReference1.BookingViewingData ViewingField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] Seats
        {
            get
            {
                return this.SeatsField;
            }
            set
            {
                this.SeatsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.BookingViewingData Viewing
        {
            get
            {
                return this.ViewingField;
            }
            set
            {
                this.ViewingField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookingViewingData", Namespace="http://schemas.datacontract.org/2004/07/TheaterService")]
    public partial class BookingViewingData : object
    {
        
        private System.DateTime DateField;
        
        private int IdField;
        
        private ServiceReference1.MovieData MovieField;
        
        private string TheaterNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.MovieData Movie
        {
            get
            {
                return this.MovieField;
            }
            set
            {
                this.MovieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TheaterName
        {
            get
            {
                return this.TheaterNameField;
            }
            set
            {
                this.TheaterNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookingSubmissionData", Namespace="http://schemas.datacontract.org/2004/07/TheaterService")]
    public partial class BookingSubmissionData : object
    {
        
        private int CustomerIdField;
        
        private int[] SeatIdsField;
        
        private int ViewingIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId
        {
            get
            {
                return this.CustomerIdField;
            }
            set
            {
                this.CustomerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] SeatIds
        {
            get
            {
                return this.SeatIdsField;
            }
            set
            {
                this.SeatIdsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ViewingId
        {
            get
            {
                return this.ViewingIdField;
            }
            set
            {
                this.ViewingIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TheaterData", Namespace="http://schemas.datacontract.org/2004/07/TheaterService")]
    public partial class TheaterData : object
    {
        
        private int IdField;
        
        private string NameField;
        
        private ServiceReference1.Seat[] SeatField;
        
        private ServiceReference1.Viewing[] ViewingField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Seat[] Seat
        {
            get
            {
                return this.SeatField;
            }
            set
            {
                this.SeatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Viewing[] Viewing
        {
            get
            {
                return this.ViewingField;
            }
            set
            {
                this.ViewingField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMovies", ReplyAction="http://tempuri.org/IService1/GetMoviesResponse")]
        ServiceReference1.MovieData[] GetMovies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMovies", ReplyAction="http://tempuri.org/IService1/GetMoviesResponse")]
        System.Threading.Tasks.Task<ServiceReference1.MovieData[]> GetMoviesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMovie", ReplyAction="http://tempuri.org/IService1/GetMovieResponse")]
        ServiceReference1.MovieData GetMovie(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMovie", ReplyAction="http://tempuri.org/IService1/GetMovieResponse")]
        System.Threading.Tasks.Task<ServiceReference1.MovieData> GetMovieAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterCustomer", ReplyAction="http://tempuri.org/IService1/RegisterCustomerResponse")]
        void RegisterCustomer(ServiceReference1.Customer newCustomer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterCustomer", ReplyAction="http://tempuri.org/IService1/RegisterCustomerResponse")]
        System.Threading.Tasks.Task RegisterCustomerAsync(ServiceReference1.Customer newCustomer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginCustomer", ReplyAction="http://tempuri.org/IService1/LoginCustomerResponse")]
        bool LoginCustomer(ServiceReference1.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginCustomer", ReplyAction="http://tempuri.org/IService1/LoginCustomerResponse")]
        System.Threading.Tasks.Task<bool> LoginCustomerAsync(ServiceReference1.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomerData", ReplyAction="http://tempuri.org/IService1/GetCustomerDataResponse")]
        ServiceReference1.CustomerData GetCustomerData(ServiceReference1.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomerData", ReplyAction="http://tempuri.org/IService1/GetCustomerDataResponse")]
        System.Threading.Tasks.Task<ServiceReference1.CustomerData> GetCustomerDataAsync(ServiceReference1.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomerDataById", ReplyAction="http://tempuri.org/IService1/GetCustomerDataByIdResponse")]
        ServiceReference1.CustomerData GetCustomerDataById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomerDataById", ReplyAction="http://tempuri.org/IService1/GetCustomerDataByIdResponse")]
        System.Threading.Tasks.Task<ServiceReference1.CustomerData> GetCustomerDataByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCustomerPass", ReplyAction="http://tempuri.org/IService1/UpdateCustomerPassResponse")]
        void UpdateCustomerPass(ServiceReference1.CustomerData customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCustomerPass", ReplyAction="http://tempuri.org/IService1/UpdateCustomerPassResponse")]
        System.Threading.Tasks.Task UpdateCustomerPassAsync(ServiceReference1.CustomerData customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCustomerMail", ReplyAction="http://tempuri.org/IService1/UpdateCustomerMailResponse")]
        void UpdateCustomerMail(ServiceReference1.CustomerData customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCustomerMail", ReplyAction="http://tempuri.org/IService1/UpdateCustomerMailResponse")]
        System.Threading.Tasks.Task UpdateCustomerMailAsync(ServiceReference1.CustomerData customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomersBookings", ReplyAction="http://tempuri.org/IService1/GetCustomersBookingsResponse")]
        ServiceReference1.BookingData[] GetCustomersBookings(int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomersBookings", ReplyAction="http://tempuri.org/IService1/GetCustomersBookingsResponse")]
        System.Threading.Tasks.Task<ServiceReference1.BookingData[]> GetCustomersBookingsAsync(int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BookViewing", ReplyAction="http://tempuri.org/IService1/BookViewingResponse")]
        bool BookViewing(ServiceReference1.BookingSubmissionData bookingData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BookViewing", ReplyAction="http://tempuri.org/IService1/BookViewingResponse")]
        System.Threading.Tasks.Task<bool> BookViewingAsync(ServiceReference1.BookingSubmissionData bookingData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterMovie", ReplyAction="http://tempuri.org/IService1/RegisterMovieResponse")]
        void RegisterMovie(ServiceReference1.Movie newMovie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterMovie", ReplyAction="http://tempuri.org/IService1/RegisterMovieResponse")]
        System.Threading.Tasks.Task RegisterMovieAsync(ServiceReference1.Movie newMovie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateMovie", ReplyAction="http://tempuri.org/IService1/UpdateMovieResponse")]
        void UpdateMovie(ServiceReference1.MovieData updatedInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateMovie", ReplyAction="http://tempuri.org/IService1/UpdateMovieResponse")]
        System.Threading.Tasks.Task UpdateMovieAsync(ServiceReference1.MovieData updatedInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveMovie", ReplyAction="http://tempuri.org/IService1/RemoveMovieResponse")]
        void RemoveMovie(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveMovie", ReplyAction="http://tempuri.org/IService1/RemoveMovieResponse")]
        System.Threading.Tasks.Task RemoveMovieAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterViewing", ReplyAction="http://tempuri.org/IService1/RegisterViewingResponse")]
        void RegisterViewing(ServiceReference1.Viewing newViewing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterViewing", ReplyAction="http://tempuri.org/IService1/RegisterViewingResponse")]
        System.Threading.Tasks.Task RegisterViewingAsync(ServiceReference1.Viewing newViewing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomers", ReplyAction="http://tempuri.org/IService1/GetCustomersResponse")]
        ServiceReference1.CustomerData[] GetCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomers", ReplyAction="http://tempuri.org/IService1/GetCustomersResponse")]
        System.Threading.Tasks.Task<ServiceReference1.CustomerData[]> GetCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveCustomer", ReplyAction="http://tempuri.org/IService1/RemoveCustomerResponse")]
        void RemoveCustomer(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveCustomer", ReplyAction="http://tempuri.org/IService1/RemoveCustomerResponse")]
        System.Threading.Tasks.Task RemoveCustomerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTheaters", ReplyAction="http://tempuri.org/IService1/GetTheatersResponse")]
        ServiceReference1.TheaterData[] GetTheaters();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTheaters", ReplyAction="http://tempuri.org/IService1/GetTheatersResponse")]
        System.Threading.Tasks.Task<ServiceReference1.TheaterData[]> GetTheatersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface IService1Channel : ServiceReference1.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiceReference1.IService1>, ServiceReference1.IService1
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceReference1.MovieData[] GetMovies()
        {
            return base.Channel.GetMovies();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.MovieData[]> GetMoviesAsync()
        {
            return base.Channel.GetMoviesAsync();
        }
        
        public ServiceReference1.MovieData GetMovie(int id)
        {
            return base.Channel.GetMovie(id);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.MovieData> GetMovieAsync(int id)
        {
            return base.Channel.GetMovieAsync(id);
        }
        
        public void RegisterCustomer(ServiceReference1.Customer newCustomer)
        {
            base.Channel.RegisterCustomer(newCustomer);
        }
        
        public System.Threading.Tasks.Task RegisterCustomerAsync(ServiceReference1.Customer newCustomer)
        {
            return base.Channel.RegisterCustomerAsync(newCustomer);
        }
        
        public bool LoginCustomer(ServiceReference1.Customer customer)
        {
            return base.Channel.LoginCustomer(customer);
        }
        
        public System.Threading.Tasks.Task<bool> LoginCustomerAsync(ServiceReference1.Customer customer)
        {
            return base.Channel.LoginCustomerAsync(customer);
        }
        
        public ServiceReference1.CustomerData GetCustomerData(ServiceReference1.Customer customer)
        {
            return base.Channel.GetCustomerData(customer);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CustomerData> GetCustomerDataAsync(ServiceReference1.Customer customer)
        {
            return base.Channel.GetCustomerDataAsync(customer);
        }
        
        public ServiceReference1.CustomerData GetCustomerDataById(int id)
        {
            return base.Channel.GetCustomerDataById(id);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CustomerData> GetCustomerDataByIdAsync(int id)
        {
            return base.Channel.GetCustomerDataByIdAsync(id);
        }
        
        public void UpdateCustomerPass(ServiceReference1.CustomerData customer)
        {
            base.Channel.UpdateCustomerPass(customer);
        }
        
        public System.Threading.Tasks.Task UpdateCustomerPassAsync(ServiceReference1.CustomerData customer)
        {
            return base.Channel.UpdateCustomerPassAsync(customer);
        }
        
        public void UpdateCustomerMail(ServiceReference1.CustomerData customer)
        {
            base.Channel.UpdateCustomerMail(customer);
        }
        
        public System.Threading.Tasks.Task UpdateCustomerMailAsync(ServiceReference1.CustomerData customer)
        {
            return base.Channel.UpdateCustomerMailAsync(customer);
        }
        
        public ServiceReference1.BookingData[] GetCustomersBookings(int customerId)
        {
            return base.Channel.GetCustomersBookings(customerId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.BookingData[]> GetCustomersBookingsAsync(int customerId)
        {
            return base.Channel.GetCustomersBookingsAsync(customerId);
        }
        
        public bool BookViewing(ServiceReference1.BookingSubmissionData bookingData)
        {
            return base.Channel.BookViewing(bookingData);
        }
        
        public System.Threading.Tasks.Task<bool> BookViewingAsync(ServiceReference1.BookingSubmissionData bookingData)
        {
            return base.Channel.BookViewingAsync(bookingData);
        }
        
        public void RegisterMovie(ServiceReference1.Movie newMovie)
        {
            base.Channel.RegisterMovie(newMovie);
        }
        
        public System.Threading.Tasks.Task RegisterMovieAsync(ServiceReference1.Movie newMovie)
        {
            return base.Channel.RegisterMovieAsync(newMovie);
        }
        
        public void UpdateMovie(ServiceReference1.MovieData updatedInfo)
        {
            base.Channel.UpdateMovie(updatedInfo);
        }
        
        public System.Threading.Tasks.Task UpdateMovieAsync(ServiceReference1.MovieData updatedInfo)
        {
            return base.Channel.UpdateMovieAsync(updatedInfo);
        }
        
        public void RemoveMovie(int id)
        {
            base.Channel.RemoveMovie(id);
        }
        
        public System.Threading.Tasks.Task RemoveMovieAsync(int id)
        {
            return base.Channel.RemoveMovieAsync(id);
        }
        
        public void RegisterViewing(ServiceReference1.Viewing newViewing)
        {
            base.Channel.RegisterViewing(newViewing);
        }
        
        public System.Threading.Tasks.Task RegisterViewingAsync(ServiceReference1.Viewing newViewing)
        {
            return base.Channel.RegisterViewingAsync(newViewing);
        }
        
        public ServiceReference1.CustomerData[] GetCustomers()
        {
            return base.Channel.GetCustomers();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CustomerData[]> GetCustomersAsync()
        {
            return base.Channel.GetCustomersAsync();
        }
        
        public void RemoveCustomer(int id)
        {
            base.Channel.RemoveCustomer(id);
        }
        
        public System.Threading.Tasks.Task RemoveCustomerAsync(int id)
        {
            return base.Channel.RemoveCustomerAsync(id);
        }
        
        public ServiceReference1.TheaterData[] GetTheaters()
        {
            return base.Channel.GetTheaters();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TheaterData[]> GetTheatersAsync()
        {
            return base.Channel.GetTheatersAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:32941/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
